# 配置数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/realpick?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
  redis:
    database: 0
    host: localhost
    port: 6379

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.realpick.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

# pagehelper
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql

# access log
server:
  port: 8080
  # 配置access日志
  tomcat:
    accesslog:
      enabled: true
      pattern: common
    basedir: C:\Software\Idea\logs\access_log